return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "astro",
      "bash",
      "css",
      "dockerfile",
      "html",
      "javascript",
      "json",
      "jsonc",
      "lua",
      "markdown",
      "ruby",
      "rust",
      "terraform",
      "toml",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
    },
  },
}
